version: "3"

services:
  airflow_db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: airflow
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
    volumes:
      - airflow_database:/var/lib/postgresql/data/


  airflow:
    build:
      context: airflow
    restart: always
    volumes:
      - ./airflow:/usr/local/airflow
      - airflow_logs:/var/log/airflow
      - airflow_data:/var/spool/airflow
    env_file:
      - .env
    ports:
      - 8080:8080
    depends_on:
      - airflow_db

volumes:
  airflow_database:
  airflow_data:
  airflow_logs: